### ISSUE TITLE
求写到梦空间自动报名脚本

### ISSUE THREAD

**Issue by DuanJunchi** [JiyeHoo/Easy-Dmkj#1]

**Comment by JiyeHoo** [comment]
没有写过脚本，只写过客户端。
项目废弃。



发自我的iPhone 13 pro


------------------ 原始邮件 ------------------
发件人: Fvduan ***@***.***&gt;
发送时间: 2022年3月1日 11:50
收件人: JiyeHoo/Easy-Dmkj ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [JiyeHoo/Easy-Dmkj] 求写到梦空间自动报名脚本 (Issue #1)





 
大佬求写到梦空间自动报名脚本，git上有个自动报名脚本源码但是太久没更新了，能看看更新吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JiyeHoo** [comment]
可以学习一下我这篇博客文章，希望对你有帮助：blog.jiyehoo.com:81/index.php/archives/310/

**Comment by JiyeHoo** [comment]
可以参考一下我这篇文章内容，希望对你学习有帮助：blog.jiyehoo.com:81/index.php/archives/310/

**Comment by 1731300623** [comment]
奈何本人技术不精，想请大佬发一下您做的第三方app，肯定不会随意传播只是自己学习参考，邮箱1731300623@qq.com
