### ISSUE TITLE
代码相关

### ISSUE THREAD

**Issue by vintingb** [JiyeHoo/Easy-Dmkj#1]
用了我的代码可以把我名字加进去吗，输入MIT协议没有要求，但是也是一个不情之请

**Comment by JiyeHoo** [comment]
不好意思，我认为我的项目并没有使用您的代码。项目在19年3月就完成了java的控制台版本，只不过没有上传。关于用pkcs5实现pkcs7填充的方法来自龙昊雪的博客这篇16年的文章：https://www.cnblogs.com/chen-lhx/p/6233954.html。如果您仍然认为我的项目有您的代码，麻烦具体指出，我会修改开源协议并增加您的署名。感谢。

**Comment by vintingb** [comment]
String data ="dataKey=t%2BZ88oeo2xscPIEBzd1JWLr%2Faae06xI9WOwwXOVRupB%2BsAsl1nj2HDpZPc3ygHRlgm0glZajSvF7FsxbGiBe%2FcykCvyhloLZfYPGGLrCZV6ZBVDBHgwg6%2Fkq87A6A%2Bp%2BmTeUyp3eZz4voIGytVkwmlofr0Jn5bgBOitzBJtnq0I%3D&data="
我不信这也有巧合

**Comment by vintingb** [comment]
固定的datakey，和我二月份的代码一摸一样，当然

**Comment by JiyeHoo** [comment]
感谢！对着https://github.com/Sheledons/daomengKJ 这个项目写的Http工具类，使用了您的常量和思路，非常感谢您的付出。我会修改：源码头部中添加注释标注原文；README文件添加说明和MIT的贡献者信息；APP内部添加“关于”页面增加您的信息。

我会关闭该issue，并在1日之内添加上述信息。如果修改之后的贡献者声明有您觉得不妥之处，请发起新的Issue。再次感谢您！
